#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef HYADTALOSADKIT_SWIFT_H
#define HYADTALOSADKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HYAdtalosAdKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@protocol HYAdtalosVideoListener;
@protocol HYAdtalosListener;
enum HYAdtalosLossReason : NSInteger;
SWIFT_CLASS_NAMED("BaseAd")
@interface HYAdtalosBaseAd : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull unitID;
@property (nonatomic) NSInteger autoRetry;
@property (nonatomic, readonly, copy) NSString * _Nonnull adResponseEventID;
@property (nonatomic, readonly, copy) NSString * _Nonnull adResponseRequestID;
/// 释放广告相关资源。具体逻辑由子类实现；基类默认为空。
- (void)destroy;
@property (nonatomic, strong) id <HYAdtalosVideoListener> _Nullable videoListener;
@property (nonatomic, strong) id <HYAdtalosListener> _Nullable listener;
@property (nonatomic, readonly) BOOL isLoaded;
- (void)load;
- (void)loadWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler SWIFT_AVAILABILITY(ios,introduced=13.0);
@property (nonatomic, readonly) int64_t price;
@property (nonatomic, readonly) int64_t winPrice;
- (BOOL)sendWinNotice;
- (BOOL)sendWinNotice:(int64_t)winPrice;
- (BOOL)sendLossNotice:(enum HYAdtalosLossReason)lossReason;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIView;
SWIFT_CLASS_NAMED("ViewAd")
@interface HYAdtalosViewAd : HYAdtalosBaseAd
@property (nonatomic, readonly, strong) UIView * _Nullable view;
- (void)destroy;
- (void)pause;
- (void)resume;
@end

SWIFT_CLASS_NAMED("BannerAd")
@interface HYAdtalosBannerAd : HYAdtalosViewAd
- (nonnull instancetype)init:(CGPoint)pos unitID:(NSString * _Nonnull)unitID OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUnitID:(NSString * _Nonnull)unitID;
@end

@class HYAdtalosJoinKey;
SWIFT_CLASS_NAMED("Configuration")
@interface HYAdtalosConfiguration : NSObject
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token appToken:(NSString * _Nonnull)appToken idfa:(NSString * _Nonnull)idfa acquireIDFA:(BOOL)acquireIDFA acquireIDFV:(BOOL)acquireIDFV acquireUserAgent:(BOOL)acquireUserAgent acquireGeoInfo:(BOOL)acquireGeoInfo acquireInstalledApps:(BOOL)acquireInstalledApps enableLocalLog:(BOOL)enableLocalLog joinKey:(HYAdtalosJoinKey * _Nonnull)joinKey joinKey2:(HYAdtalosJoinKey * _Nonnull)joinKey2 OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FeedAd")
@interface HYAdtalosFeedAd : HYAdtalosViewAd
- (nonnull instancetype)initWithFrame:(CGRect)frame unitID:(NSString * _Nonnull)unitID OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(CGPoint)pos unitID:(NSString * _Nonnull)unitID OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUnitID:(NSString * _Nonnull)unitID;
@end

@class UIViewController;
SWIFT_CLASS_NAMED("ViewControllerAd")
@interface HYAdtalosViewControllerAd : HYAdtalosViewAd
- (BOOL)showWithView:(UIView * _Nonnull)view frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (BOOL)showWithViewController:(UIViewController * _Nonnull)viewController frame:(CGRect)frame autoCloseViewController:(BOOL)autoCloseViewController SWIFT_WARN_UNUSED_RESULT;
- (BOOL)show;
@end

SWIFT_CLASS_NAMED("InterstitialAd")
@interface HYAdtalosInterstitialAd : HYAdtalosViewControllerAd
- (nonnull instancetype)initWithUnitID:(NSString * _Nonnull)unitID OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("JoinKey")
@interface HYAdtalosJoinKey : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull joinKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
- (nonnull instancetype)initWithJoinKey:(NSString * _Nonnull)joinKey version:(NSString * _Nonnull)version OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL_NAMED("Listener")
@protocol HYAdtalosListener <NSObject>
@optional
- (void)onBeforeRequest;
- (void)onLoaded;
- (void)onFailedToLoad:(NSError * _Nonnull)error;
- (void)onRendered;
/// 广告视图高度变化回调。isFinal=true 表示该高度已在稳定窗口内保持不变。
- (void)onAdViewHeightChanged:(CGFloat)height isFinal:(BOOL)isFinal;
- (void)onShown;
- (void)onClicked;
- (void)onLeftApplication;
- (void)onClosed;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, HYAdtalosLossReason, "LossReason", open) {
  HYAdtalosLossReasonBidPriceFilter = 1001,
  HYAdtalosLossReasonPriceLowFilter = 1002,
  HYAdtalosLossReasonAdmBlacklistFilter = 1003,
  HYAdtalosLossReasonCompleteFilter = 1004,
  HYAdtalosLossReasonTimeoutFilter = 1005,
  HYAdtalosLossReasonOtherFilter = 1006,
};

@class HYAdtalosNativeResponse;
SWIFT_CLASS_NAMED("NativeAd")
@interface HYAdtalosNativeAd : HYAdtalosBaseAd
@property (nonatomic, readonly, strong) HYAdtalosNativeResponse * _Nullable nativeResponse;
- (nonnull instancetype)initWithUnitID:(NSString * _Nonnull)unitID OBJC_DESIGNATED_INITIALIZER;
- (void)destroy;
@end

@class UIImage;
@class HYAdtalosVideoMetadata;
SWIFT_CLASS_NAMED("NativeResponse")
@interface HYAdtalosNativeResponse : NSObject
- (void)destroy;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nonnull subTitle;
@property (nonatomic, readonly, copy) NSString * _Nonnull desc;
@property (nonatomic, readonly, strong) UIImage * _Nullable icon;
@property (nonatomic, readonly, copy) NSString * _Nonnull iconURL;
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
@property (nonatomic, readonly, copy) NSString * _Nonnull imageURL;
@property (nonatomic, readonly, copy) NSArray<UIImage *> * _Nonnull imageList;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull imageURLList;
@property (nonatomic, readonly) NSInteger imageWidth;
@property (nonatomic, readonly) NSInteger imageHeight;
@property (nonatomic, readonly, strong) UIImage * _Nullable logo;
@property (nonatomic, readonly, copy) NSString * _Nonnull logoURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull buttonText;
@property (nonatomic, readonly) BOOL isDownloadAd;
@property (nonatomic, readonly, copy) NSString * _Nonnull developer;
@property (nonatomic, readonly, copy) NSString * _Nonnull appBundle;
@property (nonatomic, readonly, copy) NSString * _Nonnull appName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull appDesc;
@property (nonatomic, readonly, copy) NSString * _Nonnull appDescURL;
@property (nonatomic, readonly) int64_t appSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull privacyURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull permissionURL;
@property (nonatomic, readonly) BOOL hasVideo;
@property (nonatomic, readonly, copy) NSString * _Nonnull videoURL;
@property (nonatomic, readonly, strong) UIView * _Nullable videoView;
@property (nonatomic, readonly, strong) HYAdtalosVideoMetadata * _Nullable videoMetadata;
- (void)videoPlay;
- (void)videoPause;
- (void)videoMute:(BOOL)mute;
@property (nonatomic, readonly, copy) NSString * _Nonnull sldAction;
/// 自定义 MotionHintView 的缩放与位置（需在 registerViews 之后调用）
/// \param scale 缩放比例（同时作用于图片和文字），<= 0 表示不修改缩放
///
/// \param x MotionHintView 在容器视图中的 x 坐标
///
/// \param y MotionHintView 在容器视图中的 y 坐标
///
- (void)configureMotionHintViewWithScale:(CGFloat)scale x:(CGFloat)x y:(CGFloat)y;
/// 对外暴露的刷新摇一摇提示布局接口（由上层在布局变化后调用）
- (void)refreshMotionHintViewPosition;
- (void)registerViews:(UIView * _Nullable)containerView clickViews:(NSArray<UIView *> * _Nonnull)clickViews closeViews:(NSArray<UIView *> * _Nonnull)closeViews;
- (void)unregisterViews;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("RewardVideoAd")
@interface HYAdtalosRewardVideoAd : HYAdtalosViewControllerAd
- (nonnull instancetype)initWithUnitID:(NSString * _Nonnull)unitID OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL_NAMED("RewardVideoListener")
@protocol HYAdtalosRewardVideoListener <HYAdtalosListener>
@optional
- (void)onRewarded:(NSString * _Nonnull)data;
@end

SWIFT_CLASS_NAMED("SDK")
@interface HYAdtalosSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull userAgent;)
+ (NSString * _Nonnull)userAgent SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserAgent:(NSString * _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull token;)
+ (NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull appToken;)
+ (NSString * _Nonnull)appToken SWIFT_WARN_UNUSED_RESULT;
+ (void)initialize:(HYAdtalosConfiguration * _Nonnull)config;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SplashAd")
@interface HYAdtalosSplashAd : HYAdtalosViewControllerAd
- (nonnull instancetype)initWithUnitID:(NSString * _Nonnull)unitID OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL_NAMED("VideoController")
@protocol HYAdtalosVideoController
@property (nonatomic, strong) id <HYAdtalosVideoListener> _Nullable videoListener;
@property (nonatomic, readonly) BOOL isPlaying;
@property (nonatomic, readonly) BOOL isEnded;
@property (nonatomic, readonly, strong) HYAdtalosVideoMetadata * _Nullable metadata;
@property (nonatomic, readonly) BOOL hasVideo;
- (void)play;
- (void)pause;
- (void)mute:(BOOL)mute;
@end

SWIFT_PROTOCOL_NAMED("VideoListener")
@protocol HYAdtalosVideoListener <NSObject>
@optional
- (void)onVideoLoad:(HYAdtalosVideoMetadata * _Nonnull)metadata;
- (void)onVideoStart;
- (void)onVideoPlay;
- (void)onVideoPause;
- (void)onVideoEnd;
- (void)onVideoVolumeChange:(double)volume muted:(BOOL)muted;
- (void)onVideoTimeUpdate:(double)currentTime duration:(double)duration;
- (void)onVideoError;
- (void)onVideoBreak;
@end

enum HYAdtalosPlayType : NSInteger;
enum HYAdtalosStatus : NSInteger;
@class NSData;
SWIFT_CLASS_NAMED("VideoMetadata")
@interface HYAdtalosVideoMetadata : NSObject
@property (nonatomic, readonly) double duration;
@property (nonatomic, readonly) NSInteger videoWidth;
@property (nonatomic, readonly) NSInteger videoHeight;
@property (nonatomic, readonly) BOOL autoplay;
@property (nonatomic) double currentTime;
@property (nonatomic) BOOL muted;
@property (nonatomic) double volume;
@property (nonatomic) enum HYAdtalosPlayType type;
@property (nonatomic) enum HYAdtalosStatus status;
@property (nonatomic) BOOL ended;
- (NSData * _Nullable)json SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)jsonString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, HYAdtalosPlayType, "PlayType", open) {
  HYAdtalosPlayTypeFirstPlay = 1,
  HYAdtalosPlayTypeContinuePlay = 2,
  HYAdtalosPlayTypeReplay = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, HYAdtalosStatus, "Status", open) {
  HYAdtalosStatusNormal = 0,
  HYAdtalosStatusLoading = 1,
  HYAdtalosStatusError = 2,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
